### DISCUSSION TITLE
Is there a way to make the bot periodically send a command in chat?

### DISCUSSION THREAD

**Discussion by ghost** [ORelio/Minecraft-Console-Client#2264] [Q&A] [answered]
The sever I want to AFK on uses a hub system, and there is no way to directly join the survival sever (the sever that I want to AFK on). 

What I want the bot to do is to just send "/join survival" every 5 minutes or so (if i'm already in the sever it'll just say "invalid command" so it wont do any harm

**Comment by BruceChenQAQ** [comment, marked as answer]
You can use AntiAFK
```toml
[ChatBot.AntiAFK]
Enabled = true
Delay = { min = 300.0, max = 300.0 }
Command = "/join survival"
Use_Sneak = false
Use_Terrain_Handling = false
Walk_Range = 5
Walk_Retries = 20
```

Or ScriptScheduler
```toml
[ChatBot.ScriptScheduler]
Enabled = true

[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "Join Survival"
Trigger_On_First_Login = false
Trigger_On_Login = false
Trigger_On_Times = { Enable = false, Times = [ ] }
Trigger_On_Interval = { Enable = true, MinTime = 300.0, MaxTime = 300.0 }
Action = "send /join survival"
```

Or just execute it after entering the server
```toml
[ChatBot.ScriptScheduler]
Enabled = true

[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "Join Survival"
Trigger_On_First_Login = false
Trigger_On_Login = true
Trigger_On_Times = { Enable = false, Times = [ ] }
Trigger_On_Interval = { Enable = false, MinTime = 10.0, MaxTime = 10.0 }
Action = "send /join survival"
```
