### DISCUSSION TITLE
Looping Chat Message Sender

### DISCUSSION THREAD

**Discussion by SpinachIsDelicious** [ORelio/Minecraft-Console-Client#2453] [Q&A] [answered]
How do I make a simple MCC script that types /rebirth (command) into the chat every 15 minutes and then loops again?
Thank you.

**Comment by milutinke** [comment, marked as answer]
You either can use a script, or you can use Script Scheduler chat bot (https://mccteam.github.io/guide/chat-bots.html#defining-a-task)

Example for Script Scheduler:
```toml
[ChatBot.ScriptScheduler]
Enabled = true

    [[ChatBot.ScriptScheduler.TaskList]]
    Task_Name = "Rebirth command sender"
    Trigger_On_First_Login = false
    Trigger_On_Login = true # Triggers the task once you log in to the server
    Trigger_On_Times = { Enable = false, Times = [ 14:00:00, ] }
    Trigger_On_Interval = { Enable = true, MinTime = 900.0, MaxTime = 900.0 } # Loops every 15 minutes (900 seconds)
    Action = "send /rebirth"
```

To use a script, make a file, in this example I'll name it `myscript.txt`
Put the following content:
```
send /rebirth
wait 900
script myscript.txt
```
Then use `/script myscript.txt` to start the script.
(900 seconds = 15 minutes)

Replace the `myscript.txt` with your file name.
