### DISCUSSION TITLE
I want a copy of the code

### DISCUSSION THREAD

**Discussion by Sage4483** [ORelio/Minecraft-Console-Client#2702] [Q&A] [answered]
I need a script for chat bot to automatically sleep at a certain time so that it can be executed in MCC.thank you

**Comment by milutinke** [comment, marked as answer]
> I need a script for chat bot to automatically sleep at a certain time so that it can be executed in MCC.thank you

You can use the [Script Scheduler](https://mccteam.github.io/guide/chat-bots.html#script-scheduler) chat bot to run the [`bed` command](https://mccteam.github.io/guide/usage.html#bed)

For an example:
```toml
[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "Sleep"
Trigger_On_First_Login = false
Trigger_On_Login = false
Trigger_On_Times = { Enable = true, Times = [ 19:00:00, ] }
Trigger_On_Interval = { Enable = false, MinTime = 3.6, MaxTime = 4.8 }
Action = "bed sleep 50"
```

PS: This is for real world time.

For in-game time you could use something like this:
```csharp
//MCCScript 1.0

MCC.LoadBot(new CheckForSleep());

//MCCScript Extensions

public class CheckForSleep : ChatBot
{
    private DateTime nextTaskRun = DateTime.Now;
    private long timeOfDay;

    public override void OnTimeUpdate(long worldAge, long timeOfDay)
    {
        this.timeOfDay = timeOfDay;
    }
    
    public override void Update()
    {
        var dateNow = DateTime.Now;

        if (nextTaskRun < dateNow)
        {
            var (hours, minutes) = GetCurrentInGameTime();

            if (hours == 22)
            {
                PerformInternalCommand("bed 50");

                // Schedule next check to run in 15 minutes
                nextTaskRun = dateNow.AddMinutes(15);
                return;
            }

            // Schedule next check to run in 1 minute
            nextTaskRun = dateNow.AddMinutes(1);
        }
    }

    private (int hours, int minutes) GetCurrentInGameTime()
    {
        var time = this.timeOfDay;

        if (time < 0)
            time = time * -1;

        time = time % 24000;

        var hours = 6 + (int)(time / 1000);

        if (hours >= 24)
            hours -= 24;

        var minutesDouble = (double)time % 1000;
        minutesDouble = (minutesDouble / 1000) * 60;

        int minutes = (int)Math.Round(minutesDouble);

        if (minutes == 60)
        {
            minutes = 0;
            hours++;
        }

        return (hours, minutes);
    }
}
```

**Reply by Sage4483** [reply]
If you want to sleep every 60 minutes, how do you change the time

**Reply by milutinke** [reply]
```toml
Trigger_On_Times = { Enable = false, Times = [ 19:00:00, ] }
Trigger_On_Interval = { Enable = true, MinTime = 60.0, MaxTime = 60.0 }
```

**Reply by Sage4483** [reply]
I did not find the above statement in your code

**Reply by Sage4483** [reply]
Or to put it simply, I want to automatically send a sleep command every minute

**Reply by Sage4483** [reply]
Sorry, the code you provided does not automatically sleep during game night time. Could you please modify it again？

**Reply by milutinke** [reply]
It's in the Script Scheduler example, replace those 2 lines in it and put that setting into your Script Scheduler settings.
Also, enable Terrain and Inventory handling.

**Reply by Sage4483** [reply]
Is it necessary to put the modified Script Scheduler example into the MCC configuration file and then start the script you wrote？

**Reply by milutinke** [reply]
Nope, the Script Scheduler is one way of doing it, the script is another way of doing it.
The C# script is using in-game time and will sleep when it's night, while the Sleep Scheduler will execute the `bed` command every 60 real life minutes.
If you want the script, then copy the code, make a new file named `Sleep.cs`, paste the code in the file and save it, then you can start the script with `/script Sleep.cs` command or you can use Script Scheduler to run it when you log in to the server.
If you just want the Script Scheduler approach, stop the MCC, open `MinecraftClient.ini` settings file, find the `[ChatBot.ScriptScheduler]` section, set the `Enabled` field to `true`, then under it, paste the following:

```toml
[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "Sleep"
Trigger_On_First_Login = false
Trigger_On_Login = false
Trigger_On_Times = { Enable = false, Times = [ 19:00:00, ] }
Trigger_On_Interval = { Enable = true, MinTime = 60.0, MaxTime = 60.0 }
Action = "bed sleep 50"
```

Also set `TerrainAndMovements` to `true` and `InventoryHandling` to `true` (they're in the different part of the settings file).
Then save the settings file and run the mcc.

**PS: Make sure that the MCC is not running while you're editing the settings file, otherwise the changes you made will be overridden.**
